apiVersion: v1
kind: ConfigMap
metadata:
  name: ebikes-config
  namespace: ebikes
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "eureka-server"
  EUREKA_INSTANCE_PORT: "8761"
  API_GATEWAY_EUREKA_INSTANCE_PORT: "8080"
  API_GATEWAY_EUREKA_INSTANCE_HOSTNAME: "api-gateway"
  PROMETHEUS_INSTANCE_PORT: "9090"
  PROMETHEUS_INSTANCE_HOSTNAME: "prometheus"
  MONGODB_INSTANCE_HOSTNAME: "mongodb"
  MONGODB_INSTANCE_PORT: "27017"
  MONGODB_CONNECTION_STRING: "mongodb://mongodb:27017"
  USER_INSTANCE_HOSTNAME: "user-microservice"
  USER_INSTANCE_PORT: "8080"
  USER_MONGODB_COLLECTION: "users"
  USER_MONGODB_DATABASE: "users_db"
  USER_ADAPTER_RIDE_PORT: "8081"
  EBIKE_INSTANCE_HOSTNAME: "ebike-microservice"
  EBIKE_INSTANCE_PORT: "8080"
  EBIKE_MONGODB_COLLECTION: "ebikes"
  EBIKE_MONGODB_DATABASE: "ebikes_db"
  EBIKE_ADAPTER_RIDE_PORT: "8081"
  MAP_INSTANCE_HOSTNAME: "map-microservice"
  MAP_INSTANCE_PORT: "8080"
  MAP_ADAPTER_RIDE_PORT: "8081"
  MAP_ADAPTER_EBIKE_PORT: "8082"
  RIDE_INSTANCE_HOSTNAME: "ride-microservice"
  RIDE_INSTANCE_PORT: "8080"